name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust to your main branch name
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Adjust to your preferred Node.js version
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend 
      - name: Build
        run: npm run build
        working-directory: ./frontend 
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build
